workflows:
  ios-device:
    name: iOS Build for Real Device
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install --repo-update

      - name: Build iOS for Device
        script: |
          # Build for real device (arm64), NOT simulator
          flutter build ios --release --no-codesign --no-tree-shake-icons

          # Verify the build is for device
          echo "Checking architecture..."
          file build/ios/iphoneos/Runner.app/Runner

          # Create IPA
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r TaskCare.ipa Payload
          mv TaskCare.ipa $CM_BUILD_DIR/

    artifacts:
      - '*.ipa'
      - build/ios/iphoneos/*.app

    publishing:
      email:
        recipients:
          - giatufutoi@gmail.com
        notify:
          success: true
          failure: true

  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - giatufutoi@gmail.com
        notify:
          success: true
          failure: true
