workflows:
  ios-debug:
    name: iOS Debug Build (For Sideload)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install

      - name: Build iOS Debug
        script: |
          flutter build ios --debug --no-codesign
          cd build/ios/iphonesimulator || cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r Runner-debug.ipa Payload
          mv Runner-debug.ipa $CM_BUILD_DIR/

    artifacts:
      - '*.ipa'
      - build/ios/**/*.app

    publishing:
      email:
        recipients:
          - giatufutoi@gmail.com
        notify:
          success: true
          failure: true

  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - giatufutoi@gmail.com
        notify:
          success: true
          failure: true
